"""Generating code snippets."""

import symfem
from defelement.caching import load_cache, save_cache
from defelement.element import Element
from defelement.tools import jsify
from defelement.implementations import Implementation
from webtools.code_markup import python_highlight, rust_highlight, cpp_highlight


def install_info(impl: Implementation, language: str) -> str:
    """Generate installation information for a language.

    Args:
        impl: The implementation
        language: Programming language

    Returns:
        Installation info
    """
    info = f"Before running this example, you must install <a href='{impl.url}'>{impl.name}</a>"

    cmd = impl.install(language)

    if cmd is None:
        info += ". "
    else:
        info += ":<p class='pcode'>" + cmd.replace("\n", "<br />") + "</p>"
    return info


def add_to_cargo_toml(impl: Implementation) -> str:
    """Generate information about adding to Cargo.toml file.

    Args:
        impl: The implementation

    Returns:
        Installation info
    """
    info = (
        f"To running this snippet, you must add <a href='{impl.url}'>{impl.name}</a>"
        " to your Cargo.toml file"
    )

    cmd = impl.install("rust")

    if cmd is None:
        info += ". "
    else:
        info += ":<p class='pcode'>" + cmd.replace("\n", "<br />") + "</p>"
    return info


languages = {
    "python": {"name": "Python", "highlight": python_highlight},
    "rust": {"name": "Rust", "highlight": rust_highlight, "install": add_to_cargo_toml},
    "cpp": {"name": "C++", "higlight": cpp_highlight},
}


def generate_examples(e: Element, impl: Implementation, language: str) -> str | None:
    """Generate code snippets.

    Args:
        e: The element to generate examples for
        impl: The implementation to generate example for
        language: Programming language

    Returns:
        Code snippets or None if none were generated
    """
    langname = languages[language]["name"]
    jscodename = jsify(impl.id)
    if not e.implemented(impl.id):
        return None

    # Implementations generated from other implementations (eg Basix code generated by Symfem)
    if impl.id.startswith("*(") and impl.id.endswith(")"):
        cache_id = f"{e.name}-{impl.id}-implementation-code"
        c = load_cache(cache_id, symfem.__version__)
        input_code, output_code = impl.id[2:-1].split(" -> ")
        jscodename = jsify(output_code)
        if c is None:
            if not e.implemented(output_code):
                try:
                    example_code = e.make_implementation_examples(impl.id, language)
                    save_cache(cache_id, symfem.__version__, example_code)
                except (NotImplementedError, KeyError):
                    save_cache(cache_id, symfem.__version__, "_NONE")
                    return None
        else:
            if c == "_NONE":
                return None
            else:
                example_code = c
        # if e.filename in verification and output_code in verification[e.filename]:
        #    v = verification[e.filename][output_code]

    # Standard implementations
    elif e.has_implementation_examples(impl.id):
        # if e.filename in verification and impl.id in verification[e.filename]:
        #    v = verification[e.filename][impl.id]

        example_code = e.make_implementation_examples(impl.id, language)

    # Make the HTML for the examples
    info = (
        f"<a class='show_eg_link' id='show_{jscodename}_{language}_link' "
        f"href='javascript:show_{jscodename}_{language}_eg()' style='display:block'>"
        f"&darr; Show {impl.name} {langname} examples &darr;</a>"
        f"<a class='hide_eg_link' id='hide_{jscodename}_{language}_link' "
        f"href='javascript:hide_{jscodename}_{language}_eg()' style='display:none'>"
        f"&uarr; Hide {impl.name} {langname} examples &uarr;</a>"
        f"<div id='{jscodename}_{language}_eg' style='display:none'>"
    )

    if "install" in languages[language]:
        info += languages[language]["install"](impl)
    else:
        info += install_info(impl, language)

    info += (
        "This element can then be created with the following lines of "
        f"{languages[language]['name']}:"
        f"<p class='pcode'>{languages[language]['highlight'](example_code)}</p>"
        "</div>"
    )

    info += (
        "<script type='text/javascript'>\n"
        f"function show_{jscodename}_{language}_eg(){{\n"
        f" document.getElementById('show_{jscodename}_{language}_link').style.display='none'\n"
        f" document.getElementById('hide_{jscodename}_{language}_link').style.display='block'\n"
        f" document.getElementById('{jscodename}_{language}_eg').style.display='block'\n"
        "}\n"
        f"function hide_{jscodename}_{language}_eg(){{\n"
        f" document.getElementById('show_{jscodename}_{language}_link').style.display='block'\n"
        f" document.getElementById('hide_{jscodename}_{language}_link').style.display='none'\n"
        f" document.getElementById('{jscodename}_{language}_eg').style.display='none'\n"
        "}\n"
        "</script>"
    )
    return info
