on:
  push:
    branches:
      - main

jobs:
  build-website:
    name: Build defelement.com
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: sudo pip3 install -r requirements.txt
        name: Install symfem

      - run: python3 builder/build-pages.py ../_html
        name: Build website HTML
      - run: |
          cd ../_html
          git config --global user.email "symfem@mscroggs.co.uk"
          git config --global user.name "Finite Element Bot"
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Build HTML website"
          git remote add origin https://symfembot:${{ secrets.bot_github_token }}@github.com/mscroggs/defelement.com.git
          git push -u origin gh-pages --force
        name: Push website to gh-pages branch
