name: Test and build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip python3-flake8
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/mscroggs/symfem.git symfem-src
          cd symfem-src
          sudo pip3 install .
        name: Install latest symfem
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 -m flake8 builder
        name: Flake8 checks on builder
      - run: python3 -m flake8 test
        name: Flake8 checks on tests
    
  test-build-website:
    name: Test building of defelement.com
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/mscroggs/symfem.git symfem-src
          cd symfem-src
          sudo pip3 install .
        name: Install latest symfem
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 builder/build-pages.py ../_test_html --test
        name: Build website HTML

  build-website:
    name: Build defelement.com
    runs-on: ubuntu-latest
    needs:
      - test-build-website
      - run-tests
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/mscroggs/symfem.git symfem-src
          cd symfem-src
          sudo pip3 install .
        name: Install latest symfem
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 builder/build-pages.py ../_html
        name: Build website HTML
      - run: |
          cd ../_html
          git config --global user.email "symfem@mscroggs.co.uk"
          git config --global user.name "Finite Element Bot"
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Build HTML website"
          git remote add origin https://symfembot:${{ secrets.bot_github_token }}@github.com/mscroggs/defelement.com.git
          git push -u origin gh-pages --force
        name: Push website to gh-pages branch
        if: github.ref == 'refs/heads/main'

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: |
            sudo apt-get install -y python3-setuptools python3-pip python3-pytest
            sudo pip3 install pytest-xdist
        name: Install dependencies
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/mscroggs/symfem.git symfem-src
          cd symfem-src
          sudo pip3 install .
        name: Install latest symfem
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 -m pytest -n4 test
        name: Run tests with pytest
