name: Test and build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip python3-flake8
        name: Install dependencies
      - uses: actions/checkout@v2
      - name: Install Symfem
        run: sudo pip3 install git+https://github.com/mscroggs/symfem.git
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 -m flake8 builder
        name: Flake8 checks on builder
      - run: python3 -m flake8 test
        name: Flake8 checks on tests
    
  test-build-website:
    name: Test building of defelement.com
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install dependencies
      - uses: actions/checkout@v2
      - name: Install Symfem
        run: sudo pip3 install git+https://github.com/mscroggs/symfem.git

      - run: mkdir -p ~/.local/share/fonts
        name: Make font folder
      - name: Clone Varela Round
        uses: actions/checkout@v2
        with:
          path: ./varela-r
          repository: avrahamcornfeld/Varela-Round-Hebrew
          ref: master
      - run: cp varela-r/fonts/VarelaRound-Regular.otf ~/.local/share/fonts/
        name: Install Varela Round
      - name: Download and install Computer Modern
        run: |
          wget https://downloads.sourceforge.net/project/cm-unicode/cm-unicode/0.7.0/cm-unicode-0.7.0-otf.tar.xz
          tar -xf cm-unicode-0.7.0-otf.tar.xz
          cp cm-unicode-0.7.0/cmunti.otf ~/.local/share/fonts/

      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 build.py ../_test_html --test buffa-christiansen,direct-serendipity,dual,hellan-herrmann-johnson,hsieh-clough-tocher,lagrange,nedelec1,raviart-thomas,regge,serendipity,taylor-hood,vector-bubble-enriched-Lagrange
        name: Build website HTML

  build-website:
    name: Build defelement.com
    runs-on: ubuntu-latest
    needs:
      - test-build-website
      - run-tests
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install dependencies
      - uses: actions/checkout@v2
      - name: Install Symfem
        run: sudo pip3 install git+https://github.com/mscroggs/symfem.git

      - run: mkdir -p ~/.local/share/fonts
        name: Make font folder
      - name: Clone Varela Round
        uses: actions/checkout@v2
        with:
          path: ./varela-r
          repository: avrahamcornfeld/Varela-Round-Hebrew
          ref: master
      - run: cp varela-r/fonts/VarelaRound-Regular.otf ~/.local/share/fonts/
        name: Install Varela Round
      - name: Download and install Computer Modern
        run: |
          wget https://downloads.sourceforge.net/project/cm-unicode/cm-unicode/0.7.0/cm-unicode-0.7.0-otf.tar.xz
          tar -xf cm-unicode-0.7.0-otf.tar.xz
          cp cm-unicode-0.7.0/cmunti.otf ~/.local/share/fonts/

      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 build.py ../_html --github-token ${{ secrets.bot_github_token }}
        name: Build website HTML
      - run: |
          cd ../_html
          git config --global user.email "symfem@mscroggs.co.uk"
          git config --global user.name "Finite Element Bot"
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Build HTML website"
          git remote add origin https://symfembot:${{ secrets.bot_github_token }}@github.com/mscroggs/defelement.com.git
          git push -u origin gh-pages --force
        name: Push website to gh-pages branch
        if: github.ref == 'refs/heads/main'

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: |
            sudo apt-get install -y python3-setuptools python3-pip python3-pytest
            sudo pip3 install pytest-xdist
        name: Install dependencies
      - uses: actions/checkout@v2

      - name: Install Symfem
        run: sudo pip3 install git+https://github.com/mscroggs/symfem.git

      - name: Install Basix
        run: |
          sudo apt-get install -y libeigen3-dev libopenblas-dev liblapack-dev
          sudo pip3 install pybind11
          sudo pip3 install git+https://github.com/FEniCS/basix.git@mscroggs/quadrature-enum

      - name: Install UFL
        run: |
          sudo pip3 install git+https://github.com/FEniCS/ufl.git

      - name: Install Bempp-cl
        run: |
          sudo pip3 install numpy==1.20 scipy numba meshio>=4.0.16
          sudo pip3 install git+https://github.com/bempp/bempp-cl.git

      - name: Install LaTeÎ§
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base

      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 -m pytest -n4 test
        name: Run tests with pytest
