name: Verification

on:
  schedule:
    - cron: "0 7 1 * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: verification-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verification:
    permissions:
      id-token: write # Needed to make push work
      contents: write # To upload verification data
    name: Run verification
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Load Symfem cache
        id: cache-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /home/runner/.cache/symfem
          key: symfem-cache

      - name: Clone Symfem
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./symfem
          repository: mscroggs/symfem
          ref: main
          persist-credentials: false
      - name: Install Symfem
        run: |
            cd symfem
            python3 -m pip install .[optional]

      - run: python3 -m pip install .
        name: Install defelement

      - name: Install implementations
        run: |
          python3 -m pip install setuptools
          python3 install_implementations.py --install-type verification

      - name: Clone verification history
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ./verification-old
          repository: DefElement/DefElement
          ref: verification
          persist-credentials: false

      - run: |
          mkdir ../verification
          cp verification-old/verification-history.json ../verification
        name: Make verification dir containing history
      - run: python3 verify.py ../verification/verification.json --processes 4
        name: Run verification
      - run: python3 .github/scripts/push_verification.py ../verification
        name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deply-website:
    name: Build and deploy website
    needs:
      - verification
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      pages: write # Allow updating of Github Pages website
      id-token: write # Needed by pages
