name: Run tests

on:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: |
            sudo apt-get install -y python3-setuptools python3-pip python3-pytest
            sudo pip3 install pytest-xdist
        name: Install dependencies
      - uses: actions/checkout@v2

      - name: Clone Symfem
        uses: actions/checkout@v2
        with:
          path: ./symfem-src
          repository: mscroggs/symfem
          ref: main
      - run: |
          cd symfem-src
          sudo pip3 install .
        name: Install Symfem

      - name: Clone Basix
        uses: actions/checkout@v2
        with:
          path: ./basix-src
          repository: FEniCS/basix
          ref: main
      - run: |
          sudo apt-get install -y libeigen3-dev libopenblas-dev liblapack-dev ninja-build
          sudo pip3 install pybind11
        name: Install Basix dependencies
      - run: |
          cd basix-src
          ls
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DXTENSOR_ENABLE_ASSERT=ON -B build-dir -S .
          cmake --build build-dir
          sudo cmake --install build-dir
          sudo pip3 install ./python/
        name: Install Basix

      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 -m pytest -n4 test
        name: Run tests with pytest
