name: Run tests

on:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - run: |
            sudo apt-get install -y python3-setuptools python3-pip python3-pytest
            sudo pip3 install pytest-xdist
            sudo pip3 install "numpy>=1.21,<1.23" scipy numba>=0.55.2
        name: Install dependencies
      - uses: actions/checkout@v2

      - name: Clone Symfem
        uses: actions/checkout@v2
        with:
          path: ./symfem
          repository: mscroggs/symfem
          ref: plot_tikz
      - name: Install Symfem
        run: |
            cd symfem
            pip3 install .[optional]

      - name: Install Basix
        run: |
          sudo apt-get install -y libeigen3-dev libopenblas-dev liblapack-dev
          sudo pip3 install pybind11
          sudo pip3 install git+https://github.com/FEniCS/basix.git

      - name: Install UFL
        run: |
          sudo pip3 install git+https://github.com/FEniCS/ufl.git

      - name: Install Bempp-cl
        run: |
          sudo pip3 install numpy scipy numba meshio>=4.0.16
          sudo pip3 install git+https://github.com/bempp/bempp-cl.git

      - name: Install LaTeÎ§
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base

      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 -m pytest -n4 test
        name: Run tests with pytest
